spring:
  application:
    name: blockchain

  datasource:
    url: jdbc:postgresql://localhost:5432/blockchain_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true


leveldb:
  path: ./data/leveldb
  create-if-missing: true
  cache-size: 104857600

blockchain:
  genesis:
    admin-public-key: "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE6Zips/rr6D/KCuXUOjxXf/ZE8TjXR10vN7rMljQGKiQ4wd/L6iOh29PdwMRt0bo6yzIoW5ifKT1WXGxsfiSQCQ=="
  bootstrap:
    # Начальный список пиров (адреса нод для P2P). Добавляются при первом запуске, если список пиров пуст.
    peers: []
    # Пример: peers: ["http://localhost:8081", "http://192.168.1.10:8080"]